### ISSUE TITLE
DemoFull broken

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz-demo#21]
## Reproducing the problem
```bash
git clone https://github.com/VCityTeam/UD-Viz-demo
git checkout 4b0f7a5ecd1bc32f0ac6631abee28476
```
Then  [install the DemoFull sub-demo](DemoFull sub-demo). When loading it
with a web-browser one gets the error message

```bash
Uncaught (in promise) TypeError: LayerManager is not a constructor
    at BaseDemo.init3DView (BaseDemo.js:760)
    at BaseDemo.js:47
```

## Hint
On a (very) quick look, it seems that `UD-Viz:LayerManager` is involved in the trouble

## Suggestion
Note that the CI didn't detect this UD-Viz-demo bug because it reveals itself at runtime (as opposed
to build time) which happens quite often with scripting languages. Maybe it is time for UD-Viz to come up with some testing to be integrated in the CI ?

**Comment by mathieuLivebardon** [comment]
Some files were moved, and when importing the components into BaseDemo.js the path was not updated correctly.

Here is the correction of the lines to be changed:

```js 
//src/Helper/BaseDemo.js lines 5,6,7
const ModuleView = Widgets.Components.ModuleView;
const TilesManager = Widgets.Components.TilesManager;
const LayerManager = Widgets.Components.LayerManager;
```

**Comment by mathieuLivebardon** [comment]
It's fix on master, now you can debug Demofull.
